manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/4nh3k
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:   
    path: config
